### PR TITLE
Added QuickSave compatibility

### PR DESCRIPTION
**Pull request by RealSweetPanda**

### CODE REVIEW

**Comment by NermNermNerm** [comment]
Hi!  Can you give me some pointers to what QuickSave is?  Is that a save-in-the-middle-of-the-day kind of mod?  How thoroughly have you tested this?

**Comment by RealSweetPanda** [comment]
QuickSave description is "Save your game midday RPG-Style.". basically saving midday and loading midday. Now I tested it only a bit but it basically just runs the code the mod runs in order to work with normal saves, but before the midday save and after the midday save. my testing was: be near the tractor terrain feature to make sure it exists, save and if there's errors and then load midday and check if there's any errors and making sure it still exists. there were no errors and the tractor was still there.

**Comment by NermNermNerm** [comment]
Can you give it a more thorough shakedown?  Use it in a playthrough, something like that?  If I add this to the mod and I get a bug report, it's gonna be me that has to figure it out.  That can take a while with something that I'm not familiar with.  I'd really like to be confident that there aren't many surprises in it before committing it.

**Comment by RealSweetPanda** [comment]
Ok, so I tested it in a full playthrough and everything worked, I saved many many times and loaded many many times
some of the examples are (all of them I both midday saved and midday loaded):
near the broken loader, while still on the ground
broken loader in inventory
while loader is being repaired
while building garage
while garage is built but tractor is broken
while tractor is broken but added the harvester
while tractor is fixed, still in garage
while tractor is fixed, player on tractor
while broken engine is inside the chest
and many more, there's no point to list because they test the exact same thing or because I forgot. I tried every time there is something slightly different that is related to the mod, to save midday and load. everything works perfect.

**Pull request merged**
